### ISSUE TITLE
Channel definitions should be stored in external db

### ISSUE THREAD

**Issue by benapetr** [valhallasw/pywikibugs#11]
Hardcoding a list of channels is not a best thing to do, it should be stored in some external file and read runtime when modified, so that bot can be dynamically updated without having to reboot it

**Comment by yuvipanda** [comment]
Highly dislike. Channels shouldn't be changed that often. Plus this introduces a state keeping mechanism that would be unneeded otherwise and keep the codebase much simpler.

**Comment by benapetr** [comment]
I agree that it would keep codebase simple, as well as it would keep the functionality pretty limited, which applies for every software - more functions = more code. Not implementing this, will make it significantly easier for developers, and significantly harder for regular users. So it's basically a choice between being a lazy developer or developer who cares about users of their product :P

**Comment by valhallasw** [comment]
I don't see why this is useful. Changing channels doesn't (and shouldn't) happen often, and the current configuration style allows a lot of flexibility in setting up filters. Making a DSL won't make life easier, and I'll gladly spend a few minutes of my time helping someone set up a channel to save a few hours of development and debugging time.
