### ISSUE TITLE
List of channels and feeds should be modifiable through IRC

### ISSUE THREAD

**Issue by benapetr** [valhallasw/pywikibugs#12]
So that people can insert easily the bot to any other channel without having to modify its source code

**Comment by yuvipanda** [comment]
Dislike. Then it will have to keep state somehow and that just adds complexity to the code majorly.

**Comment by benapetr** [comment]
So you basically dislike having to code it :P

**Comment by valhallasw** [comment]
See #11, and this is IMO even more problematic: this introduces the need for the bot to respond to users, authentication, etc.
