### ISSUE TITLE
Stray space between inferred email name and closing parenthesis

### ISSUE THREAD

**Issue by Krinkle** [valhallasw/pywikibugs#26]
Whenever wikibugs guesses the name (by using the first portion of the e-mail address), it outputs an extra space.

> wikibugs: VisualEditor / ContentEditable: VisualEditor: Typing fast in reference dialog box shifts the first character of the text to the next line in Firefox - https://bugzilla.wikimedia.org/64399#c5 **(ryasmeen )** Verified the fix in Betalabs with Firefox 27.0.1
> wikibugs: VisualEditor / Editing Tools: VisualEditor: 0,0 initial selection in Firefox when opening a new or pre-existing references means inserting template causes fatal JS error - https://bugzilla.wikimedia.org/64434#c1 **(James Forrester)** ASS>RES/FIX a:Ed Sanders Fixed in the Firefox-selection change E...

**Comment by valhallasw** [comment]
Corresponding mail is in ~/testcases/003296.raw

**Comment by valhallasw** [comment]
Fixed!
