### ISSUE TITLE
Close repo since it got moved to Gerrit?

### ISSUE THREAD

**Issue by hashar** [valhallasw/pywikibugs#28]
It seems the repository pywikibugs is now hosted on Wikimedia Gerrit: ssh://gerrit.wikimedia.org:29418/labs/tools/pywikibugs.git

https://git.wikimedia.org/summary/?r=labs/tools/pywikibugs.git

Maybe it should be closed entirely to avoid confusion?

**Comment by hashar** [comment]
The reason I found out this github repository is because it is pointed to from Bugzilla component: Tools Labs Tools > wikibugs IRC bot

I have filled https://bugzilla.wikimedia.org/show_bug.cgi?id=69696 to have the link to the git repository to be changed to point to the repository hosted on Wikimedia Gerrit.

**Comment by valhallasw** [comment]
Thanks for filing the bugzilla fix bug -- I have emptied the repo now (well, almost, but I'm too lazy to get the last few files out :-p)

**Comment by hashar** [comment]
Thank you!
